### ISSUE TITLE
[Add]: Open Image Dataset

### ISSUE THREAD

**Issue by Ameya02** [PriyansuMaurya/AI-Fusion#13]
### Site URL

https://storage.googleapis.com/openimages/web/index.html

### Description

The Open Images Dataset by Google is a collection of millions of labeled images that can be used for computer vision tasks. It includes images of different things like objects, scenes, and activities, and each image has annotations to describe what's in it. The dataset is regularly updated and can be used for tasks like recognizing objects in images or understanding what's happening in a scene. It's widely used by researchers and developers to train and evaluate computer vision models.

### Category

Datasets 📊

### Checklist

- [X] I have checked the existing issues.
- [X] I have read the [Contributing Guidelines](https://github.com/PriyansuMaurya/AI-Fusion/blob/main/CONTRIBUTING.md).
- [X] I am willing to work on this issue (optional).

**Comment by PriyansuMaurya** [comment]
All add tags
