### ISSUE TITLE
[Add]: AWS Open Data Registry

### ISSUE THREAD

**Issue by Ameya02** [PriyansuMaurya/AI-Fusion#15]
### Site URL

https://registry.opendata.aws/

### Description

The AWS Open Data Registry is a platform provided by Amazon Web Services (AWS) that offers access to a wide range of publicly available datasets. These datasets cover various domains such as climate, healthcare, finance, and more. The registry makes it easier for users to discover and access these datasets, which can be used for research, analysis, and building applications. AWS provides tools and services to help users efficiently process and analyze these datasets in the cloud.
### Category

Datasets 📊

### Checklist

- [X] I have checked the existing issues.
- [X] I have read the [Contributing Guidelines](https://github.com/PriyansuMaurya/AI-Fusion/blob/main/CONTRIBUTING.md).
- [X] I am willing to work on this issue (optional).

**Comment by PriyansuMaurya** [comment]
LGTM, tags?

**Comment by Ameya02** [comment]
Ok
