### ISSUE TITLE
[Add]: Adobe Podcast , Github Copilot

### ISSUE THREAD

**Issue by Ameya02** [PriyansuMaurya/AI-Fusion#21]
### Site URL

https://podcast.adobe.com/

### Description

Adobe Podcast
Adobe Podcast is a web-based audio recording and editing tool that utilizes artificial intelligence (AI) to enhance the quality of audio recordings. It offers a range of features that make it a powerful tool for podcasters. Additionally, it allows for remote recording and provides automatic transcription capabilities.
Github Copilot
https://marketplace.visualstudio.com/items?itemName=GitHub.copilotvsGitHub 
Copilot is an AI-powered code completion tool developed by GitHub in collaboration with OpenAI. It uses machine learning models to assist developers by suggesting code snippets and completing lines of code as they write. With Copilot, developers can increase their productivity, save time, and gain insights from its extensive knowledge base, which includes code from popular open-source projects.
Dall E
https://openai.com/dall-e-2
DALL·E is an advanced image generation model developed by OpenAI. It uses a combination of deep learning and generative adversarial networks (GANs) to create unique and highly realistic images from textual descriptions. DALL·E can understand and interpret written prompts to generate corresponding images, often with surprising and imaginative results. This groundbreaking AI technology opens up new possibilities for creative expression, visual storytelling, and artistic exploration.
Looka
https://looka.com/
Looka is an AI-powered logo design platform that allows users to create professional logos with ease. It provides a simple and intuitive interface, along with a vast library of design elements, fonts, and color palettes to choose from. Looka's intelligent algorithms generate customized logo options based on user preferences, making it a valuable tool for businesses and individuals looking for high-quality branding.

### Category

Tools 🔧

### Checklist

- [X] I have checked the existing issues.
- [X] I have read the [Contributing Guidelines](https://github.com/PriyansuMaurya/AI-Fusion/blob/main/CONTRIBUTING.md).
- [X] I am willing to work on this issue (optional).

**Comment by PriyansuMaurya** [comment]
Wrong Description of Adobe Podcast

Correct one: Adobe Podcast is a web-based audio recording and editing tool with AI capabilities. It allows remote recording, offers automatic transcription, enhances audio quality with AI-powered features, and enables collaboration among podcasters.

Copilot correct link : https://marketplace.visualstudio.com/items?itemName=GitHub.copilotvs
tag for Copilot: "extension", "vscode" and more according to you

**Comment by Ameya02** [comment]
Ok will update the following changes
