### ISSUE TITLE
[Bug]: Footer should remain at bottom

### ISSUE THREAD

**Issue by Ameya02** [PriyansuMaurya/AI-Fusion#29]
### Description

The footer should be positioned at the bottom of the page on every page and remain persistent.

### Attach Screenshots (if applicable)

Currently, the footer doesn't stick to the bottom on all devices. This problem is not visible on mobile devices.

![Inkedaifusion vercel app_ (1)](https://github.com/PriyansuMaurya/AI-Fusion/assets/101447544/c0ea1ca1-e866-4257-85d3-8c051c053c6b)

It should stick to the bottom like this:

![image](https://github.com/PriyansuMaurya/AI-Fusion/assets/65841021/d1a4965d-8bd4-4e0f-947c-fac8a0378547)

### Which browser are you using when experiencing the issue?

Brave

### Checklist

- [X] I have checked for existing issues related to this problem.
- [X] I have read the [Contributing Guidelines](https://github.com/PriyansuMaurya/AI-Fusion/blob/main/CONTRIBUTING.md).
- [ ] I am willing to work on this issue (optional).

**Comment by CYBWEBALI** [comment]
Can you assign this issue to me?

**Comment by PriyansuMaurya** [comment]
sure, why not?

**Comment by CYBWEBALI** [comment]
Done PR #32 .
