### ISSUE TITLE
[Feature]: Modify Browser Tab Title When Visiting Pages Other Than the Home Page.

### ISSUE THREAD

**Issue by PriyansuMaurya** [PriyansuMaurya/AI-Fusion#36]
### Description

Browser tab title should changes when the user visits (tools, prompts or datasets) to

HOME    : AI Fusion
Tools      : AI Fusion - Tools
Prompts : AI Fusion - Prompts
Datasets : AI Fusion - Datasets

### Provide Screenshot

CURRENT: 
![AI-Fusion - Personal - Microsoft​ Edge 6_29_2023 7_19_27 PM](https://github.com/PriyansuMaurya/AI-Fusion/assets/101447544/1718cd23-561b-4e2b-890b-59c4e49f004b)

![AI-Fusion - Personal - Microsoft​ Edge 6_29_2023 7_23_56 PM](https://github.com/PriyansuMaurya/AI-Fusion/assets/101447544/dc50b4c1-8b45-4b42-8630-767e67442df8)
title is same for remaning tabs

REQUIRED: 
The homepage title should remain as it is. 
![AI-Fusion - Personal - Microsoft​ Edge 6_29_2023 7_30_05 PM](https://github.com/PriyansuMaurya/AI-Fusion/assets/101447544/c55c6ad7-ac73-45e4-8632-c72d95e24d88)
It should work same for the remaning tabs (prompts and datasets).

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/PriyansuMaurya/AI-Fusion/blob/main/CONTRIBUTING.md).
- [ ] I am willing to work on this issue (optional)

**Comment by the-shivam-gupta** [comment]
Hello @PriyansuMaurya, I would like to make the necessary changes can u plz assign it to me.
