### ISSUE TITLE
[Bug]: <Need to be proper responsive for galaxy fold devices>

### ISSUE THREAD

**Issue by Brijesh1963** [PriyansuMaurya/AI-Fusion#42]
### Description

Need to be proper responsive for galaxy fold devices ......
![responsiveness](https://github.com/PriyansuMaurya/AI-Fusion/assets/98037970/799be205-fbf7-49f5-b668-29deefba1d32)

### Which browser are you using when experiencing the issue?

Chrome

### Checklist

- [X] I have checked for existing issues related to this problem.
- [X] I have read the [Contributing Guidelines](https://github.com/PriyansuMaurya/AI-Fusion/blob/main/CONTRIBUTING.md).
- [X] I am willing to work on this issue (optional).

**Comment by PriyansuMaurya** [comment]
Amazing! You may proceed.

**Comment by PriyansuMaurya** [comment]
@Brijesh1963 are you working on this issue?
