### ISSUE TITLE
[Feature]: Sort the cards in alphabetical order.

### ISSUE THREAD

**Issue by the-shivam-gupta** [PriyansuMaurya/AI-Fusion#55]
### Description

Cards in the tools, prompts, and datasets sections are randomly assigned.

### Provide Screenshot

Image1:
![image](https://github.com/PriyansuMaurya/AI-Fusion/assets/109647722/ddaf018b-28ec-4668-854b-41cd653abdff)

Image2:
![image](https://github.com/PriyansuMaurya/AI-Fusion/assets/109647722/e06c64e6-50fe-40a0-aa27-8aea80eff60b)

Image3:
![image](https://github.com/PriyansuMaurya/AI-Fusion/assets/109647722/bc085c5e-402e-4a67-b3e1-fcd222013804)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/PriyansuMaurya/AI-Fusion/blob/main/CONTRIBUTING.md).
- [X] I am willing to work on this issue (optional)

**Comment by PriyansuMaurya** [comment]
Go ahead!
