### ISSUE TITLE
Add: SlidesAI

### ISSUE THREAD

**Issue by the-shivam-gupta** [PriyansuMaurya/AI-Fusion#59]
### Site URL

https://www.slidesai.io/

### Description

SlidesAI is an online platform that uses advanced AI algorithms to create visually striking and informative **presentations** quickly and easily. It's a game-changing tool for businesses and individuals looking to improve their visual communication and save time.

### Category

Tools 🔧

### Checklist

- [X] I have checked the existing issues.
- [X] I have read the [Contributing Guidelines](https://github.com/PriyansuMaurya/AI-Fusion/blob/main/CONTRIBUTING.md).
- [X] I am willing to work on this issue (optional).

**Comment by PriyansuMaurya** [comment]
have you used it?

**Comment by the-shivam-gupta** [comment]
Yes I have and it really works amazing.
