### ISSUE TITLE
[Bug]: Problem in buttons switching from light to dark mode and vice-versa.

### ISSUE THREAD

**Issue by the-shivam-gupta** [PriyansuMaurya/AI-Fusion#61]
### Description

When you click on the "Tools," "Prompts," or "Dataset" sections, the background color turns green, like this:

![image](https://github.com/PriyansuMaurya/AI-Fusion/assets/109647722/f8b6b0d9-dc56-4107-8c01-cff4ad3f9e0f)

When you change from light mode to dark mode, the button you clicked on doesn't look the same as before. For example, if you were using light mode and switched to dark mode, the green background on the selected button disappeared.

![image](https://github.com/PriyansuMaurya/AI-Fusion/assets/109647722/f188937e-5276-484c-a78a-fff66e220bcb)

### Which browser are you using when experiencing the issue?

Chrome

### Checklist

- [X] I have checked for existing issues related to this problem.
- [X] I have read the [Contributing Guidelines](https://github.com/PriyansuMaurya/AI-Fusion/blob/main/CONTRIBUTING.md).
- [X] I am willing to work on this issue (optional).

**Comment by PriyansuMaurya** [comment]
You might wanna check this out for implementing this

https://tailwindcomponents.com/component/simple-tab-button
